[package]
name = "xiao-soil-moisture-sensor-matter-thread"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "soil_sensor_core"
path = "src/lib.rs"

[[bin]]
name = "xiao-soil-moisture-sensor-matter-thread"
path = "src/main.rs"
harness = false

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
opt-level = "s"
overflow-checks = false

[profile.dev]
opt-level = "s"

[features]
default = ["esp32c6", "trouble", "thread"]
trouble = ["rs-matter-embassy/trouble"]
esp32c6 = [
  "esp-rtos/esp32c6",
  "esp-hal/esp32c6",
  "esp-backtrace/esp32c6",
  "esp-println/esp32c6",
  "esp-radio/esp32c6",
  "esp-storage/esp32c6",
  "esp-bootloader-esp-idf/esp32c6",
  "esp-metadata-generated/esp32c6",
  "portable-atomic/critical-section",
]
thread = [
  "rs-matter-embassy/openthread",
  "rs-matter-embassy/mbedtls",
  "rs-matter-embassy/openthread-heap-int-8192",
]

[dependencies]
log = "0.4"
embassy-executor = "0.10"
embassy-embedded-hal = "0.6"
embassy-futures = "0.1"
embassy-time = "0.5"
embassy-sync = "0.8"
esp-backtrace = { version = "0.20", features = ["panic-handler", "println"] }
esp-hal = { version = "~1.2", features = ["log-04", "unstable", "exception-handler"] }
esp-rtos = { version = "0.4", features = ["esp-radio", "embassy"] }
esp-alloc = "0.11"
esp-println = { version = "0.18", features = ["log-04"] }
esp-radio = { version = "1.0.0-beta.0", features = ["ble", "log-04", "unstable"] }
esp-storage = { version = "0.10", features = ["embedded-storage"] }
esp-bootloader-esp-idf = { version = "0.6", features = ["log-04"] }
esp-metadata-generated = "0.5"

rs-matter-embassy = { git = "https://github.com/sysgrok/rs-matter-embassy", default-features = false, features = [
  "esp",
  "log",
] }

sequential-storage = "8"
embedded-storage-async = "0.4.1"

tinyrlibc = { version = "0.5", default-features = false, features = ["memchr", "utoa", "strtoul"] }
static_cell = "2"
portable-atomic = "1"

[patch.crates-io]
esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-alloc = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-println = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-radio = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-storage = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
esp-metadata-generated = { git = "https://github.com/esp-rs/esp-hal", rev = "0fed45c84c0723ed4e0b7d19c7f3078ed79090c6" }
